[package]
name = "shredder"
description = "A Garbage Collector for Rust"
categories = ["gc", "garbage collector"]
keywords = ["gc"]

authors = ["Gregor Peach <gregorpeach@gmail.com>"]
repository = "https://github.com/Others/shredder"
readme = "README.md"
license = "MIT"

version = "0.1.0"
edition = "2018"

[dependencies]
crossbeam = "0.7.3"
dashmap = "3.11"
dynqueue = "0.1.2"
log = "0.4.8"
once_cell = "1.4"
parking_lot = "0.10.0"
rayon = "1.3"
rental = "0.5.5"
shredder_derive = { git = "https://github.com/Others/shredder_derive.git" }
#shredder_derive = { path = "../shredder_derive" }
stable_deref_trait = "1.1"

[dev-dependencies]
rand = "0.7.3"
trybuild = "1.0"

#[profile.release]
#debug = true
