[package]
name = "shredder"
description = "An experimental Garbage Collector for Rust"
categories = ["gc", "garbage collector"]
keywords = ["gc"]

authors = ["Gregor Peach <gregorpeach@gmail.com>"]
repository = "https://github.com/Others/shredder"
readme = "README.md"
license = "MIT"

version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.8"
once_cell = "1.2"
parking_lot = "0.10.0"
